version: "3.0"

services:
  unifiapibrowser:
    image: scyto/unifibrowser
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - USER=pcw
      - "PASSWORD=${TEST_UNIFI_CONTROLLER_PASS}"
      - "UNIFIURL=${TEST_UNIFI_CONTROLLER_BASE_URL}"
      - DISPLAYNAME=Philly Community Wireless
      - PORT=8443
      - APIBROWSERUSER=pcw_test
      - "APIBROWSERPASS=${API_BROWSER_PASS_HASH}"

      # vv== This MUST be 0 ==vv
      - NOAPIBROWSERAUTH=0
