version: "3.0"

services:
  unifiapibrowser:
    image: quinnbatten/unifibrowser:2.0.25
    ports:
      - 8000:8000
    environment:
      - USER=apibrowser
      - "PASSWORD=${UNIFI_PASS}"
      - "UNIFIURL=${UNIFI_URL}"
      - DISPLAYNAME=Philly Community Wireless
      - PORT=8443
      - "APIBROWSERUSER=${APIBROWSER_USER}"
      - "APIBROWSERPASS={APIBROWSER_PASS}"

      # vv== This MUST be 0 ==vv
      - NOAPIBROWSERAUTH=0
